# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""Backend that generates meson.build files from moz.build files."""

import os
from collections import defaultdict

import mozpack.path as mozpath

from mozbuild.backend.base import PartialBackend
from mozbuild.frontend.data import (
    BaseProgram,
    HostLibrary,
    HostProgram,
    HostSources,
    Program,
    SharedLibrary,
    Sources,
    StaticLibrary,
)
from mozbuild.util import FileAvoidWrite


class MesonBackend(PartialBackend):
    """Backend that generates meson.build files.
    
    This backend converts TreeMetadata objects from moz.build files
    into meson.build files that can be used with the Meson build system.
    """

    def _init(self):
        """Initialize the backend state."""
        # Track meson.build content for each directory
        self._meson_files = defaultdict(list)
        
        # Track sources for each target
        self._target_sources = defaultdict(list)
        self._target_host_sources = defaultdict(list)
        
        # Track programs and libraries
        self._programs = {}
        self._libraries = {}
        
        # Track the current directory being processed
        self._current_dir = None

    def consume_object(self, obj):
        """Process a single TreeMetadata object.
        
        Args:
            obj: A TreeMetadata object from the frontend
            
        Returns:
            True if the object was handled, False otherwise
        """
        if isinstance(obj, (Sources, HostSources)):
            return self._handle_sources(obj)
        elif isinstance(obj, (Program, HostProgram)):
            return self._handle_program(obj)
        elif isinstance(obj, (StaticLibrary, SharedLibrary, HostLibrary)):
            return self._handle_library(obj)
        
        # We don't handle this object type
        return False

    def _handle_sources(self, obj):
        """Handle Sources and HostSources objects."""
        # Group sources by directory
        objdir = obj.objdir
        
        if isinstance(obj, HostSources):
            for source in obj.files:
                self._target_host_sources[objdir].append(str(source))
        else:
            for source in obj.files:
                self._target_sources[objdir].append(str(source))
        
        return True

    def _handle_program(self, obj):
        """Handle Program and HostProgram objects."""
        self._programs[obj.objdir] = {
            'name': obj.program,
            'is_host': isinstance(obj, HostProgram),
            'objdir': obj.objdir,
            'srcdir': obj.srcdir,
        }
        return True

    def _handle_library(self, obj):
        """Handle library objects (static, shared, host)."""
        lib_name = getattr(obj, 'basename', None) or getattr(obj, 'lib_name', 'unknown')
        
        self._libraries[obj.objdir] = {
            'name': lib_name,
            'is_static': isinstance(obj, StaticLibrary),
            'is_shared': isinstance(obj, SharedLibrary),
            'is_host': isinstance(obj, HostLibrary),
            'objdir': obj.objdir,
            'srcdir': obj.srcdir,
        }
        return True

    def consume_finished(self):
        """Called when all objects have been consumed.
        
        This generates the actual meson.build files.
        """
        # Generate meson.build files for each directory that has build targets
        all_dirs = set()
        all_dirs.update(self._programs.keys())
        all_dirs.update(self._libraries.keys())
        all_dirs.update(self._target_sources.keys())
        all_dirs.update(self._target_host_sources.keys())
        
        for objdir in all_dirs:
            self._generate_meson_build(objdir)
        
        # Generate the top-level meson.build file
        self._generate_top_level_meson_build()

    def _generate_meson_build(self, objdir):
        """Generate a meson.build file for a specific directory."""
        content_lines = []
        content_lines.append("# Generated by mozbuild's Meson backend")
        content_lines.append("")
        
        # Add sources if any
        sources = self._target_sources.get(objdir, [])
        host_sources = self._target_host_sources.get(objdir, [])
        
        # Add program if any
        program = self._programs.get(objdir)
        if program:
            src_list = sources or host_sources
            if src_list:
                content_lines.append(f"# Program: {program['name']}")
                content_lines.append("sources = [")
                for src in src_list:
                    # Convert path to be relative to srcdir
                    content_lines.append(f"  '{src}',")
                content_lines.append("]")
                content_lines.append("")
                
                exe_name = program['name']
                if program['is_host']:
                    content_lines.append(f"executable('{exe_name}', sources, native: true)")
                else:
                    content_lines.append(f"executable('{exe_name}', sources)")
                content_lines.append("")
        
        # Add library if any
        library = self._libraries.get(objdir)
        if library:
            src_list = sources or host_sources
            if src_list:
                content_lines.append(f"# Library: {library['name']}")
                content_lines.append("sources = [")
                for src in src_list:
                    content_lines.append(f"  '{src}',")
                content_lines.append("]")
                content_lines.append("")
                
                lib_name = library['name']
                if library['is_shared']:
                    content_lines.append(f"shared_library('{lib_name}', sources)")
                elif library['is_static']:
                    content_lines.append(f"static_library('{lib_name}', sources)")
                else:
                    content_lines.append(f"library('{lib_name}', sources)")
                content_lines.append("")
        
        # Only write the file if there's actual content
        if len(content_lines) > 2:  # More than just the header
            # Write to objdir
            meson_build_path = mozpath.join(objdir, "meson.build")
            
            with self._write_file(meson_build_path) as fh:
                fh.write("\n".join(content_lines))

    def _generate_top_level_meson_build(self):
        """Generate the top-level meson.build file."""
        content_lines = []
        content_lines.append("# Top-level meson.build generated by mozbuild")
        content_lines.append("")
        content_lines.append("project('mozilla', 'c', 'cpp',")
        content_lines.append("  version: '1.0',")
        content_lines.append("  default_options: ['warning_level=3'])")
        content_lines.append("")
        
        # Find all subdirectories that have meson.build files
        subdirs = set()
        for objdir in set(list(self._programs.keys()) + list(self._libraries.keys())):
            # Get relative path from topobjdir
            reldir = mozpath.relpath(objdir, self.environment.topobjdir)
            if reldir and reldir != '.':
                subdirs.add(reldir)
        
        if subdirs:
            content_lines.append("# Subdirectories")
            for subdir in sorted(subdirs):
                content_lines.append(f"subdir('{subdir}')")
            content_lines.append("")
        
        top_meson_build = mozpath.join(self.environment.topobjdir, "meson.build")
        
        with self._write_file(top_meson_build) as fh:
            fh.write("\n".join(content_lines))
