---
# SPDX-License-Identifier: MPL-2.0

name: Daily Runtime Build

permissions:
  contents: write

'on':
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug build'
        required: false
        type: boolean
        default: true
      pgo:
        description: 'Enable Profile-Guided Optimization'
        required: false
        type: boolean
        default: true
      omnijar_compress:
        description: 'Omni.ja compression algorithm'
        required: false
        type: choice
        options:
          - deflate
          - zstd
          - lz4
          - none
        default: deflate

run-name: Daily Runtime Build${{ (inputs.debug || github.event_name == 'schedule') && ' (Debug)' || '' }}

jobs:
  windows-x86_64:
    name: Windows x86_64
    uses: ./.github/workflows/wrapper-build-windows.yml
    secrets: inherit
    with:
      debug: ${{ github.event.inputs.debug == 'true' || github.event_name == 'schedule' }}
      pgo:  ${{ github.event.inputs.pgo == 'true' && github.event_name != 'schedule' }}
      omnijar_compress: ${{ github.event.inputs.omnijar_compress || 'deflate' }}

  linux-x86_64:
    name: Linux x86_64
    uses: ./.github/workflows/wrapper-build-linux.yml
    secrets: inherit
    with:
      debug: ${{ github.event.inputs.debug == 'true' || github.event_name == 'schedule' }}
      pgo:  ${{ github.event.inputs.pgo == 'true' && github.event_name != 'schedule' }}
      omnijar_compress: ${{ github.event.inputs.omnijar_compress || 'deflate' }}

  linux-aarch64:
    name: Linux aarch64
    uses: ./.github/workflows/wrapper-build-linux.yml
    secrets: inherit
    with:
      debug: ${{ github.event.inputs.debug == 'true' || github.event_name == 'schedule' }}
      pgo:  ${{ github.event.inputs.pgo == 'true' && github.event_name != 'schedule' }}
      arch: aarch64
      omnijar_compress: ${{ github.event.inputs.omnijar_compress || 'deflate' }}
