# SPDX-License-Identifier: MPL-2.0

name: "(A) ⚒ Linux build"

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: true
      pgo:
        description: 'Enable native Profile-Guided Optimization (PGO)'
        type: boolean
        default: false
        required: true

  workflow_call:
    inputs:
      debug:
        type: boolean
        required: true
      pgo:
        description: 'Enable native Profile-Guided Optimization (PGO)'
        type: boolean
        default: false
        required: true

run-name: ${{ toJSON(inputs.pgo) == 'true' && '[Native PGO] '||'' }}Linux x64 build${{ toJSON(inputs.debug) == 'true' && ' Debug'||'' }}
jobs:
  run-main:
    name: Linux-x64
    uses: ./.github/workflows/common-build.yml
    with:
      platform: linux
      arch: x86_64
      debug: ${{ inputs.debug }}
      pgo: ${{ inputs.pgo }}
