# SPDX-License-Identifier: MPL-2.0

name: "(A) ⚒ Windows build"

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug build'
        type: boolean
        required: true
      pgo:
        description: 'Enable PGO/profile generation'
        type: boolean
        default: false
        required: true

  workflow_call:
    inputs:
      debug:
        description: 'Enable debug build'
        type: boolean
        required: true
      pgo:
        description: 'Enable PGO/profile generation'
        type: boolean
        default: false
        required: true

run-name: ${{ toJSON(inputs.pgo) == 'true' && '[PGO] ' || '' }}Windows x64 build${{ toJSON(inputs.debug) == 'true' && ' Debug' || '' }}

jobs:
  # Non-PGO build (single stage)
  build-normal:
    name: Windows x64 build${{ toJSON(inputs.debug) == 'true' && ' Debug' || '' }}
    if: ${{ toJSON(inputs.pgo) != 'true' }}
    uses: ./.github/workflows/common-build.yml
    with:
      platform: windows
      arch: x86_64
      debug: ${{ inputs.debug }}
      pgo: false

  # PGO build stage 1: Profile generation
  build-pgo-stage1:
    name: Windows x64 PGO Stage 1 - Profile Generation${{ toJSON(inputs.debug) == 'true' && ' Debug' || '' }}
    if: ${{ toJSON(inputs.pgo) == 'true' }}
    uses: ./.github/workflows/common-build.yml
    with:
      platform: windows
      arch: x86_64
      debug: ${{ inputs.debug }}
      pgo: true
      pgo_mode: 'generate'

  # PGO build stage 2: Run profile collection
  collect-profiles:
    name: Windows x64 PGO Stage 2 - Collect Profiles
    if: ${{ toJSON(inputs.pgo) == 'true' }}
    needs: build-pgo-stage1
    uses: ./.github/workflows/pgo-build.yml
    secrets: inherit
    with:
      browser-artifact-name: noraneko-windows-x86_64-profile-generate-mode-package
      artifact-path: C:\artifact
      runner: windows-latest
      target-arch: x86_64
      profile-mode: generate
      upload-artifact-name: noraneko-windows-x86_64-profile-generate-output

  # PGO build stage 3: Build with collected profiles
  build-pgo-final:
    name: Windows x64 PGO Stage 3 - Final Build${{ toJSON(inputs.debug) == 'true' && ' Debug' || '' }}
    if: ${{ toJSON(inputs.pgo) == 'true' }}
    needs: collect-profiles
    uses: ./.github/workflows/common-build.yml
    with:
      platform: windows
      arch: x86_64
      debug: ${{ inputs.debug }}
      pgo: true
      pgo_mode: 'use'
      pgo_artifact_name: noraneko-windows-x86_64-profile-generate-output
